
variables:
  REACT_BUILD_DIR: build

deploy_frontend:
  stage: deploy
  image: node:18
  script:
    - npm install
    - npm run build
    - npm install -g firebase-tools
    - echo "$FIREBASE_TOKEN" > token.txt
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
  only:
    - firebase
  artifacts:
    paths:
      - $REACT_BUILD_DIR
